### ISSUE TITLE
feature: Support prefix to git tag

### ISSUE THREAD

**Issue by shivajivarma** [Optum/semver-cli#27]
## Feature Request

Add support for prefix to version tag like `--prefix-tag v` -> git tag `v1.0.0`

This would help in CI automation on version tags.

Example GitHub action for releases.
```
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
```
